name: redus_flutter
description: Vue-like Component system for Flutter with reactive state and lifecycle hooks.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.0
  redus:
    path: ../redus_dart

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
